/* Generated by Cython 3.1.2 */

#ifndef __PYX_HAVE_API__efl__eo
#define __PYX_HAVE_API__efl__eo
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"

static PyObject *(*__pyx_api_f_3efl_2eo_object_from_instance)(Eo *) = 0;
#define object_from_instance __pyx_api_f_3efl_2eo_object_from_instance
static Eo *(*__pyx_api_f_3efl_2eo_instance_from_object)(PyObject *) = 0;
#define instance_from_object __pyx_api_f_3efl_2eo_instance_from_object
static int __Pyx_ImportFunction_3_1_2(PyObject *module, const char *funcname, void (**f)(void), const char *sig);

#ifndef __PYX_HAVE_RT_ImportFunction_3_1_2
#define __PYX_HAVE_RT_ImportFunction_3_1_2
static int __Pyx_ImportFunction_3_1_2(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, "__pyx_capi__");
    if (!d)
        goto bad;
#if (defined(Py_LIMITED_API) && Py_LIMITED_API >= 0x030d0000) || (!defined(Py_LIMITED_API) && PY_VERSION_HEX >= 0x030d0000)
    PyDict_GetItemStringRef(d, funcname, &cobj);
#else
    cobj = PyDict_GetItemString(d, funcname);
    Py_XINCREF(cobj);
#endif
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    Py_DECREF(cobj);
    return 0;
bad:
    Py_XDECREF(d);
    Py_XDECREF(cobj);
    return -1;
}
#endif


static int import_efl__eo(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("efl.eo");
  if (!module) goto bad;
  if (__Pyx_ImportFunction_3_1_2(module, "object_from_instance", (void (**)(void))&__pyx_api_f_3efl_2eo_object_from_instance, "PyObject *(Eo *)") < 0) goto bad;
  if (__Pyx_ImportFunction_3_1_2(module, "instance_from_object", (void (**)(void))&__pyx_api_f_3efl_2eo_instance_from_object, "Eo *(PyObject *)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__efl__eo */
